# Generated by Django 3.0.8 on 2020-07-23 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raven', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_desc', models.CharField(max_length=200)),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raven.Location')),
            ],
        ),
    ]
