# Generated by Django 3.0.8 on 2020-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raven', '0003_auto_20200723_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(),
        ),
    ]
